---

- name: "create artifact directory"
  become: true
  file:
    path: ~/artifact
    state: directory

- name: "extract archived artifact"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ~/artifact

- name: "start app with pm2"
  become: true
  shell: |
    cd ~/artifact
    npm install 
    pm2 stop default 
    pm2 start npm -- start